import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Overlay from "@/components/Overlay";
import Scroll from "@/components/Scroll";
import Copyright from "@/components/Copyright";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b-2">
          <div className="container mx-auto">
            <Navbar />
          </div>
        </div>
        {children}
        <div className="bg-footer relative">
          <Scroll />
          <Footer />
        </div>
        <Copyright />
      </body>
    </html>
  );
}
